
				[package]
				name = "herryskitties-runtime-wasm"
				version = "1.0.0"
				edition = "2018"

				[lib]
				name = "herryskitties_runtime"
				crate-type = ["cdylib"]

				[dependencies]
				wasm_project = { package = "herryskitties-runtime", path = "/root/substrate/herryskitties/runtime", default-features = false }
			